### ISSUE TITLE
Cannot find Module named core.utils

### ISSUE THREAD

**Issue by AndreDuarte00** [psychok7/pinax-notifications-backends#8]
I was installing the backends but I keep running into this error:

```python
Unhandled exception in thread started by <function wrapper at 0x7f977aa31aa0>
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
fn(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
autoreload.raise_last_exception()
File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
six.reraise(*_exception)
File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
fn(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
app_config.import_models(all_models)
File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
self.models_module = import_module(models_module_name)
File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
File "/usr/local/lib/python2.7/site-packages/pinax/notifications_backends/models.py", line 15, in <module>
from pinax.notifications.models import NoticeType, LanguageStoreNotAvailable, \
File "/usr/local/lib/python2.7/site-packages/pinax/notifications/models.py", line 17, in <module>
from .conf import settings
File "/usr/local/lib/python2.7/site-packages/pinax/notifications/conf.py", line 46, in <module>
class PinaxNotificationsAppConf(AppConf):
File "/usr/local/lib/python2.7/site-packages/appconf/base.py", line 74, in __new__
new_class._configure()
File "/usr/local/lib/python2.7/site-packages/appconf/base.py", line 103, in _configure
value = callback(value)
File "/usr/local/lib/python2.7/site-packages/pinax/notifications/conf.py", line 68, in configure_backends
backend_instance = load_path_attr(backend_path)(label, spam_sensitivity)
File "/usr/local/lib/python2.7/site-packages/pinax/notifications/conf.py", line 30, in load_path_attr
raise ImproperlyConfigured("Error importing {0}: '{1}'".format(module, e))
django.core.exceptions.ImproperlyConfigured: Error importing pinax.notifications_backends.backends.email: 'No module named core.utils'
```

Thanks in advance for any help!

**Comment by psychok7** [comment]
@AndreDuarte00 there is indeed a bug, and i think its because i am importing this https://github.com/psychok7/pinax-notifications-backends/blob/master/pinax/notifications_backends/backends/email.py#L6 that does not exist (it existed in my own project) instead of importing from the utils in this pinax project.

I will fix this as soon as i can but meanwhile a workaround would be for you to create a django app called `core` and inside a `utils.py`. Inside that file put the following code here https://github.com/psychok7/pinax-notifications-backends/blob/master/pinax/notifications_backends/utils.py

Let me know if that works

**Comment by softkrates** [comment]
Try to change        
from core.utils  import get_class_from_path   
to 
from ..utils import get_class_from_path

**Comment by NadavK** [comment]
If not for your comment @softkrates, I would not have managed to use this project.
BTW, the file to edit is `pinax/notifications_backends/backends/email.py`

**Comment by psychok7** [comment]
Feel free to create a PR addressing this issue guys I will gladly merge it. By the way from a quick look it's almost all the files in backends folder
